"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Subject = "Physics" | "Chemistry" | "Mathematics" | "Hindi" | "English";
type MCQ = { question: string; options: string[]; answer: number; explanation?: string };
const chapters: Record<Subject, string[]> = {
  Physics: ["Electric Charges & Fields", "Electrostatic Potential & Capacitance", "Current Electricity", "Moving Charges & Magnetism", "Magnetism & Matter", "Electromagnetic Induction", "Alternating Current", "Electromagnetic Waves", "Ray Optics & Optical Instruments", "Wave Optics", "Dual Nature of Radiation & Matter", "Atoms", "Nuclei", "Semiconductor Electronics"],
  Chemistry: ["Solutions", "Electrochemistry", "Chemical Kinetics", "d- and f-Block Elements", "Coordination Compounds", "Haloalkanes & Haloarenes", "Alcohols, Phenols & Ethers", "Aldehydes, Ketones & Carboxylic Acids", "Amines", "Biomolecules", "Polymers", "Chemistry in Everyday Life"],
  Mathematics: ["Relations & Functions", "Inverse Trigonometric Functions", "Matrices", "Determinants", "Continuity & Differentiability", "Applications of Derivatives", "Integrals", "Applications of Integrals", "Differential Equations", "Vector Algebra", "Three Dimensional Geometry", "Probability"],
  Hindi: ["आत्मपरिचय", "एक गीत", "पतंग", "कविता के बहाने", "कैमरे में बंद अपाहिज", "सहर्ष स्वीकारा है", "उषा", "बादल राग", "कवितावली", "लक्ष्मण-मूर्छा और राम का विलाप", "रुबाइयाँ", "छोटा मेरा खेत", "बगुलों के पंख", "सिल्वर वैडिंग", "जूझ", "अतीत में दबे पाँव", "डायरी के पन्ने"],
  English: ["The Last Lesson", "Lost Spring", "Deep Water", "The Rattrap", "Indigo", "Poets and Pancakes", "The Interview", "Going Places", "My Mother at Sixty-Six", "An Elementary School Classroom in a Slum", "Keeping Quiet", "A Thing of Beauty", "A Roadside Stand", "Aunt Jennifer's Tigers", "The Third Level", "The Tiger King", "Journey to the End of the Earth", "The Enemy", "On the Face of It", "Memories of Childhood"]
};

export default function QuizPage(){
  const [subject,setSubject]=useState<Subject>("Chemistry"); const [chapter,setChapter]=useState("Solutions"); const [count,setCount]=useState(10); const [language,setLanguage]=useState("English");
  const [questions,setQuestions]=useState<MCQ[]>([]); const [index,setIndex]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [score,setScore]=useState(0); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{const p=new URLSearchParams(window.location.search);const s=p.get("subject") as Subject|null;if(s&&chapters[s]){setSubject(s);setChapter(p.get("chapter")||chapters[s][0]);}},[]);
  useEffect(()=>{if(!chapters[subject].includes(chapter))setChapter(chapters[subject][0]);},[subject,chapter]);
  async function start(){setLoading(true);setMessage("");setQuestions([]);setIndex(0);setSelected(null);setScore(0);try{const res=await fetch("/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:`Create ${count} Class 12 ${subject} MCQs for chapter "${chapter}" in ${language}. Return ONLY valid JSON array. Each item must have question:string, options:string[4], answer:number from 0-3, explanation:string. Questions must be accurate, chapter-specific and educational.`,context:`Lakshya Quiz — chapter-wise MCQ generation. Subject ${subject}, chapter ${chapter}, language ${language}.`})});const d=await res.json();if(!res.ok)throw new Error(d.error||"Quiz generation failed");let raw=String(d.text||"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const parsed=JSON.parse(raw) as MCQ[];if(!Array.isArray(parsed)||!parsed.length)throw new Error("No MCQs returned.");setQuestions(parsed.map(q=>({...q,options:Array.isArray(q.options)?q.options.slice(0,4):[]})).filter(q=>q.options.length===4));}catch(e){setMessage(e instanceof Error?e.message:"Could not generate quiz. Try again.");}finally{setLoading(false);}}
  function choose(i:number){if(selected!==null)return;setSelected(i);if(i===questions[index].answer)setScore(s=>s+1);}
  function next(){if(index+1<questions.length){setIndex(i=>i+1);setSelected(null);}else setMessage(`Quiz complete — ${score}/${questions.length} correct.`);}
  const q=questions[index];
  return <main className="quiz"><header><Link href="/study">← Study</Link><div><span>LAKSHYA • QUIZ</span><h1>Chapter MCQ Arena</h1><p>Choose any Class 12 subject and chapter. Hindi and English chapters are included too.</p></div></header>
    <section className="setup"><div className="selects"><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value as Subject)}>{Object.keys(chapters).map(s=><option key={s}>{s}</option>)}</select></label><label>Chapter<select value={chapter} onChange={e=>setChapter(e.target.value)}>{chapters[subject].map(c=><option key={c}>{c}</option>)}</select></label><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>English</option><option>Hindi</option><option>Hinglish</option></select></label><label>Questions<select value={count} onChange={e=>setCount(Number(e.target.value))}><option value={5}>5</option><option value={10}>10</option><option value={20}>20</option></select></label></div><button className="primary" disabled={loading} onClick={()=>void start()}>{loading?"Generating…":"Start MCQ Quiz →"}</button></section>
    {message&&<div className="notice">{message}</div>}
    {q&&<section className="question"><div className="meta"><span>Question {index+1} / {questions.length}</span><b>Score {score}</b></div><div className="bar"><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div><h2>{q.question}</h2><div className="options">{q.options.map((o,i)=><button key={i} className={selected===i?(i===q.answer?"correct":"wrong"):selected!==null&&i===q.answer?"correct":""} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{selected!==null&&<div className="explanation"><b>{selected===q.answer?"✓ Correct":"✕ Not quite"}</b><p>{q.explanation||`Correct answer: ${q.options[q.answer]}`}</p><button className="primary" onClick={next}>{index+1===questions.length?"Finish":"Next Question →"}</button></div>}</section>}
    <style jsx>{`body{background:#f6f7fb}.quiz{max-width:980px;margin:auto;padding:28px 20px 70px;color:#171a2b}.quiz header{display:flex;gap:16px;margin-bottom:16px}.quiz header>a{color:#6d7482;text-decoration:none;font-size:10px;font-weight:800}.quiz header div{flex:1}.quiz header span{font-size:8px;letter-spacing:.15em;color:#9299a8;font-weight:900}.quiz h1{font-size:30px;margin:5px 0}.quiz header p{font-size:10px;color:#858c9c}.setup,.question{background:#fff;border:1px solid #e4e6ef;border-radius:16px;padding:18px;margin-bottom:13px}.selects{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.selects label{font-size:8px;color:#858c9c;font-weight:800}.selects select{display:block;width:100%;box-sizing:border-box;margin-top:5px;padding:9px;border:1px solid #e0e3eb;border-radius:8px;background:#fff;font-size:9px}.primary{border:0;background:#1b1d2b;color:#fff;border-radius:9px;padding:10px 14px;font-size:9px;font-weight:800}.notice{background:#1b1d2b;color:#fff;border-radius:10px;padding:10px;font-size:9px;margin-bottom:12px}.meta{display:flex;justify-content:space-between;font-size:9px;color:#777f90}.bar{height:6px;background:#eeeef5;border-radius:99px;margin:9px 0 20px;overflow:hidden}.bar i{display:block;height:100%;background:#6b5cff}.question h2{font-size:18px;line-height:1.5;margin-bottom:15px}.options{display:grid;gap:8px}.options button{padding:12px;text-align:left;border:1px solid #e1e4ec;background:#fff;border-radius:9px;font-size:10px;cursor:pointer}.options button.correct{border-color:#25a36f;background:#effaf5}.options button.wrong{border-color:#dc6d72;background:#fff1f2}.explanation{margin-top:15px;padding:13px;border-radius:10px;background:#f7f7fb;font-size:9px}.explanation p{line-height:1.6}.explanation .primary{margin-top:5px}@media(max-width:700px){.quiz{padding:20px 14px 80px}.selects{grid-template-columns:1fr 1fr}.quiz h1{font-size:25px}}`}</style>
  </main>;
}
