"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type ProgressMap = Record<string, number>;
export default function Revision(){
 const [uid,setUid]=useState<string|null>(null); const [progress,setProgress]=useState<ProgressMap>({});
 useEffect(()=>{let alive=true;let unsub=()=>{};(async()=>{try{const [{auth},{onAuthStateChanged}]=await Promise.all([import("@/lib/firebase"),import("firebase/auth")]);if(!alive)return;unsub=onAuthStateChanged(auth,u=>setUid(u?.uid??null),()=>setUid(null));}catch{if(alive)setUid(null)}})();return()=>{alive=false;unsub()}},[]);
 useEffect(()=>{if(!uid){setProgress({});return}let alive=true;let unsub=()=>{};(async()=>{try{const [{db},{collection,onSnapshot}]=await Promise.all([import("@/lib/firebase"),import("firebase/firestore")]);if(!alive)return;unsub=onSnapshot(collection(db,"users",uid,"chapterProgress"),s=>{const p:ProgressMap={};s.forEach(d=>p[d.id]=Number(d.data().progress)||0);setProgress(p)},()=>{});}catch{}})();return()=>{alive=false;unsub()}},[uid]);
 const completed=useMemo(()=>Object.values(progress).filter(v=>v>=100).length,[progress]);
 return <main className="simple-page"><div className="simple-head"><div><p className="eyebrow">SMART RECALL</p><h1>Revision</h1><p className="muted">A revision workspace based on your real chapter progress and practice history.</p></div><Link className="primary" href="/practice">Start practice</Link></div><section className="section-grid"><div className="panel"><p className="eyebrow">COMPLETED CHAPTERS</p><h2 style={{fontSize:32,margin:"7px 0"}}>{uid?completed:"—"}</h2><p className="muted">{uid?"Recorded from your Firebase progress":"Sign in to see your progress"}</p></div><div className="panel"><p className="eyebrow">BEST NEXT MOVE</p><h2 style={{fontSize:19,margin:"7px 0"}}>Review mistakes</h2><p className="muted">Incorrect practice attempts are the strongest signal for targeted revision.</p><Link className="secondary" href="/mistakes">Open Mistake Book →</Link></div></section><section className="card-list" style={{marginTop:16}}><div className="section-title"><h2>Revision workflow</h2><span>Real data only</span></div><div className="person-card"><div className="subject-icon">01</div><div className="person-info"><strong>Study</strong><small>Complete concepts and record chapter progress.</small></div><Link className="primary" href="/study">Open</Link></div><div className="person-card"><div className="subject-icon">02</div><div className="person-info"><strong>Mistake Book</strong><small>Revisit chapters where your practice attempts were incorrect.</small></div><Link className="primary" href="/mistakes">Open</Link></div><div className="person-card"><div className="subject-icon">03</div><div className="person-info"><strong>Fresh practice</strong><small>Generate a new chapter set with Lakshya AI when you are ready.</small></div><Link className="primary" href="/practice">Open</Link></div></section></main>
}
