"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Task={id:string;title:string;subjectId?:string;date:string;time?:string;durationMinutes:number;completed:boolean};
const subjects=["Physics","Chemistry","Mathematics","Practice","Revision","Other"];
const today=()=>{const d=new Date();const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,"0");const day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};
const formatDate=(value:string)=>new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long"}).format(new Date(`${value}T00:00:00`));

export default function PlannerPage(){
 const [uid,setUid]=useState<string|null>(null); const [tasks,setTasks]=useState<Task[]>([]); const [selectedDate,setSelectedDate]=useState(today());
 const [title,setTitle]=useState(""); const [subjectId,setSubjectId]=useState("Physics"); const [time,setTime]=useState("18:00"); const [duration,setDuration]=useState(60);
 const [adding,setAdding]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{let alive=true;(async()=>{try{const [{auth},{onAuthStateChanged}]=await Promise.all([import("@/lib/firebase"),import("firebase/auth")]);if(!alive)return;const unsub=onAuthStateChanged(auth,u=>{setUid(u?.uid??null);if(!u)setLoading(false);},()=>setLoading(false));return()=>unsub();}catch{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 async function loadTasks(userId:string,date:string){setLoading(true);setError("");try{const [{db},{collection,getDocs,query,where}]=await Promise.all([import("@/lib/firebase"),import("firebase/firestore")]);const snap=await getDocs(query(collection(db,"users",userId,"plannerTasks"),where("date","==",date)));const next=snap.docs.map(d=>({id:d.id,...d.data()} as Task)).sort((a,b)=>(a.time||"").localeCompare(b.time||""));setTasks(next);}catch(e){setError(e instanceof Error?e.message:"Could not load your plan.")}finally{setLoading(false)}}
 useEffect(()=>{if(uid)loadTasks(uid,selectedDate);else setTasks([])},[uid,selectedDate]);
 async function addTask(e:FormEvent){e.preventDefault();if(!uid||!title.trim())return;setAdding(true);setError("");try{const {savePlannerTask}=await import("@/lib/study-storage");await savePlannerTask(uid,{title:title.trim(),subjectId,date:selectedDate,time,durationMinutes:Math.max(5,Number(duration)),completed:false});setTitle("");await loadTasks(uid,selectedDate);}catch(e){setError(e instanceof Error?e.message:"Could not save task.")}finally{setAdding(false)}}
 async function toggle(task:Task){if(!uid)return;setError("");try{const {updatePlannerTask}=await import("@/lib/study-storage");await updatePlannerTask(uid,task.id,{completed:!task.completed});setTasks(prev=>prev.map(t=>t.id===task.id?{...t,completed:!t.completed}:t));}catch(e){setError(e instanceof Error?e.message:"Could not update task.")}}
 async function remove(task:Task){if(!uid)return;try{const {deletePlannerTask}=await import("@/lib/study-storage");await deletePlannerTask(uid,task.id);setTasks(prev=>prev.filter(t=>t.id!==task.id));}catch(e){setError(e instanceof Error?e.message:"Could not delete task.")}}
 const minutes=useMemo(()=>tasks.reduce((n,t)=>n+(t.durationMinutes||0),0),[tasks]); const completed=tasks.filter(t=>t.completed).length;
 return <main className="page planner-page"><div className="hero-row"><div><p className="eyebrow">PLAN WITH PURPOSE</p><h1>Study Planner</h1><p className="muted">A real plan that stays with you across devices.</p></div><Link className="secondary" href="/goals">View goals →</Link></div>
  {!uid&&!loading&&<section className="notice-card"><div><strong>Sign in to save your planner.</strong><p>Your sessions will sync to your Lakshya account instead of disappearing on refresh.</p></div><Link className="primary" href="/auth">Sign in</Link></section>}
  {error&&<div className="practice-error">{error}</div>}
  <section className="panel planner-builder"><div className="panel-head"><div><p className="eyebrow">BUILD A SESSION</p><h2>Add to your plan</h2></div><span className="tag">{minutes} MIN PLANNED</span></div><form onSubmit={addTask} className="builder-grid"><label>Task<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Electrostatics revision" required/></label><label>Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>Date<input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)} required/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><label>Duration<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={25}>25 min</option><option value={45}>45 min</option><option value={60}>60 min</option><option value={90}>90 min</option><option value={120}>120 min</option></select></label><button className="primary" disabled={!uid||adding}>{adding?"Saving…":"Add session +"}</button></form></section>
  <section className="panel planner-list"><div className="panel-head"><div><p className="eyebrow">YOUR SCHEDULE</p><h2>{formatDate(selectedDate)}</h2></div><span className="tag">{completed}/{tasks.length} COMPLETE</span></div>
   {loading?<div className="empty-state"><div className="loader">✦</div><div><h3>Loading your plan…</h3><p className="muted">Syncing your saved sessions.</p></div></div>:!uid?<div className="empty-state"><div className="empty-icon">＋</div><div><h3>Your planner is waiting</h3><p className="muted">Sign in to create and save sessions.</p></div></div>:tasks.length===0?<div className="empty-state"><div className="empty-icon">＋</div><div><h3>No sessions planned</h3><p className="muted">Add one realistic block instead of trying to plan everything at once.</p></div></div>:tasks.map(task=><div className={`timeline-item ${task.completed?"planner-done":""}`} key={task.id}><div className="time">{task.time||"—"}</div><div className="dot"/><div className="session"><span className="tag">{task.subjectId||"Study"}</span><h3>{task.title}</h3><small>{task.durationMinutes} min</small></div><button className={task.completed?"primary":"secondary"} onClick={()=>toggle(task)}>{task.completed?"✓ Done":"Complete"}</button><button className="planner-delete" aria-label={`Delete ${task.title}`} onClick={()=>remove(task)}>×</button></div>)}
  </section>
  <div className="planner-nav"><button className="secondary" onClick={()=>setSelectedDate(today())}>Today</button><button className="secondary" onClick={()=>{const d=new Date(`${selectedDate}T00:00:00`);d.setDate(d.getDate()-1);setSelectedDate(d.toISOString().slice(0,10))}}>← Previous</button><button className="secondary" onClick={()=>{const d=new Date(`${selectedDate}T00:00:00`);d.setDate(d.getDate()+1);setSelectedDate(d.toISOString().slice(0,10))}}>Next →</button></div>
  <style jsx>{`.planner-builder,.planner-list{max-width:1000px;margin:0 auto 16px}.planner-builder{padding:20px}.builder-grid{display:grid;grid-template-columns:2fr 1.2fr 1.1fr 1fr 1fr auto;gap:10px;align-items:end;margin-top:15px}.builder-grid label{font-size:9px;color:#777f90;font-weight:800;text-transform:uppercase;letter-spacing:.5px}.builder-grid input,.builder-grid select{display:block;width:100%;margin-top:6px;border:1px solid #e1e4ec;background:#fff;border-radius:11px;padding:11px;font-size:11px;color:#252a3b;outline:none;box-sizing:border-box}.planner-list{padding:20px}.planner-list .timeline-item{position:relative}.planner-list .session{min-width:0}.planner-done .session h3{text-decoration:line-through;opacity:.58}.planner-delete{border:0;background:transparent;font-size:20px;opacity:.45;cursor:pointer;padding:8px}.planner-delete:hover{opacity:1}.planner-nav{max-width:1000px;margin:auto;display:flex;gap:8px;justify-content:flex-end}.loader{animation:spin 1s linear infinite;color:#635bff}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:1100px){.builder-grid{grid-template-columns:1fr 1fr 1fr}.builder-grid button{grid-column:1/-1}}@media(max-width:700px){.builder-grid{grid-template-columns:1fr}.planner-nav{justify-content:flex-start;flex-wrap:wrap}.planner-list,.planner-builder{padding:16px}.planner-list .timeline-item{grid-template-columns:52px 14px 1fr auto}.planner-delete{grid-column:4;grid-row:1}.planner-list .timeline-item>button:not(.planner-delete){grid-column:3/5;justify-self:start;margin-top:4px}}`}</style>
 </main>
}
