"use client";
import { useMemo, useState } from "react";

type Vacancy = { id:string; title:string; organization:string; level:string; sector:string; location:string; status:string; deadline:string; pay:string; description:string; official:string; notification:string };

const vacancies: Vacancy[] = [
 {id:"ssc-calendar",title:"SSC 2026–27 Exam Calendar",organization:"Staff Selection Commission",level:"10th / 12th / Graduate",sector:"Central",location:"All India",status:"Calendar",deadline:"Dates vary by examination",pay:"Post-wise",description:"Official calendar covering major SSC recruitment examinations.",official:"https://ssc.gov.in/",notification:"https://ssc.gov.in/api/attachment/uploads/masterData/ExamCalendar/Tentative_Calendar2026_27_08012026.pdf"},
 {id:"upsc-active",title:"UPSC Active Examinations",organization:"Union Public Service Commission",level:"Graduate",sector:"Central",location:"All India",status:"Open",deadline:"Check individual notification",pay:"Post-wise",description:"Official UPSC examination and recruitment updates.",official:"https://www.upsc.gov.in/",notification:"https://www.upsc.gov.in/examinations/active-exams"},
 {id:"employment-news",title:"Employment News — Latest Jobs",organization:"Employment News / Government of India",level:"10th / 12th / Graduate",sector:"Central",location:"All India",status:"Open",deadline:"Post-wise",pay:"Post-wise",description:"Government job listings published through the official Employment News portal.",official:"https://employmentnews.gov.in/newemp/home.aspx",notification:"https://employmentnews.gov.in/newemp/AllJobs.aspx?k=All"},
 {id:"upsc-circulars",title:"UPSC Vacancy Circulars",organization:"Union Public Service Commission",level:"Graduate",sector:"Central",location:"All India",status:"Source",deadline:"Circular-wise",pay:"Post-wise",description:"Official vacancy circulars published by UPSC.",official:"https://www.upsc.gov.in/",notification:"https://www.upsc.gov.in/vacancy-circulars"},
 {id:"rrb-alp-2026",title:"RRB ALP CEN 01/2026",organization:"Railway Recruitment Boards",level:"10th / Diploma",sector:"Central",location:"All India",status:"Open",deadline:"See official CEN",pay:"Pay Level 2",description:"Assistant Loco Pilot recruitment notification. Check the official CEN and your selected RRB for exact eligibility and dates.",official:"https://www.rrbcdg.gov.in/",notification:"https://www.rrbcdg.gov.in/uploads/2026/01-ALP/012026ALP-CEN.pdf"},
 {id:"ibps-rrb-officers-xv",title:"IBPS RRB Officers XV",organization:"IBPS",level:"Graduate",sector:"Central",location:"Participating RRBs",status:"Open",deadline:"21 Sep 2026",pay:"Post-wise",description:"Common Recruitment Process for RRB Officers Scale I, II and III. Registration is listed by IBPS for 1–21 September 2026.",official:"https://www.ibps.in/",notification:"https://ibpsreg.ibps.in/rrbxvaug26/index.php?stat=0"},
 {id:"ibps-rrb-office-assistant-xv",title:"IBPS RRB Office Assistants XV",organization:"IBPS",level:"Graduate",sector:"Central",location:"Participating RRBs",status:"Open",deadline:"21 Sep 2026",pay:"Post-wise",description:"Common Recruitment Process for RRB Office Assistants (Multipurpose). Check the official notice for eligibility and dates.",official:"https://www.ibps.in/",notification:"https://ibpsreg.ibps.in/rrboaxvaug26/index.php?stat=0"},
 {id:"ibps-ongoing",title:"IBPS Other Ongoing Recruitments",organization:"IBPS",level:"Graduate",sector:"Central",location:"All India",status:"Open",deadline:"Post-wise",pay:"Post-wise",description:"IBPS lists ongoing recruitments from participating banks and financial institutions. Open the official list for current posts.",official:"https://www.ibps.in/",notification:"https://www.ibps.in/"},
 {id:"indiapost-gds",title:"India Post GDS Online Engagement",organization:"Department of Posts, Government of India",level:"10th",sector:"Central",location:"All India",status:"Source",deadline:"Schedule-wise",pay:"Post-wise",description:"Official GDS online engagement portal with notification and circle-wise post information.",official:"https://indiapostgdsonline.gov.in/",notification:"https://indiapostgdsonline.gov.in/HomePageS/D01.aspx"},
 {id:"up-rojgaar-sangam",title:"UP Rojgaar Sangam Job Search",organization:"Government of Uttar Pradesh",level:"10th / 12th / Graduate",sector:"State",location:"Uttar Pradesh",status:"Open",deadline:"Job-wise",pay:"Job-wise",description:"Official UP employment portal covering job search, employment fairs and employer listings.",official:"https://rojgaarsangam.up.gov.in/home",notification:"https://rojgaarsangam.up.gov.in/home"},
 {id:"upsssc",title:"UPSSSC Recruitment & Notices",organization:"Uttar Pradesh Subordinate Services Selection Commission",level:"12th / Graduate",sector:"State",location:"Uttar Pradesh",status:"Source",deadline:"Advertisement-wise",pay:"Post-wise",description:"Official UPSSSC recruitment notices and application updates. Always check the individual advertisement.",official:"https://upsssc.gov.in/",notification:"https://upidadv.up.gov.in/"},
 {id:"up-rural-livelihood",title:"UP State Rural Livelihood Mission Vacancies",organization:"Government of Uttar Pradesh",level:"Graduate",sector:"State",location:"Uttar Pradesh",status:"Source",deadline:"Notice-wise",pay:"Post-wise",description:"Official UP government publication portal includes vacancy notices for the Uttar Pradesh State Rural Livelihood Mission.",official:"https://information.up.gov.in/",notification:"https://information.up.gov.in/en/hi-other-information-new.aspx"},
 {id:"urise-jobs",title:"UP RISe Job & Campus Listings",organization:"Government of Uttar Pradesh / URISE",level:"Diploma / Graduate",sector:"State",location:"Uttar Pradesh",status:"Open",deadline:"Job-wise",pay:"Job-wise",description:"UP RISe employment and campus job listings, including private-sector and internship opportunities.",official:"https://urise.up.gov.in/",notification:"https://urise.up.gov.in/frontend/Homepage/jobstnp"}
,
 {id:"ncs-national",title:"National Career Service — India",organization:"Government of India / Ministry of Labour & Employment",level:"10th / 12th / Diploma / Graduate",sector:"National",location:"All India",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"National one-stop career portal covering government and private jobs, internships, job fairs, counselling and skill opportunities.",official:"https://ncs.gov.in/",notification:"https://ncs.gov.in/"},
 {id:"state-chhattisgarh",title:"Chhattisgarh Employment Portal",organization:"Government of Chhattisgarh",level:"10th / 12th / Graduate",sector:"State",location:"Chhattisgarh",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official state employment portal listed by the National Career Service government portal directory.",official:"https://erojgar.cg.gov.in/LandingSite/en/Home.aspx",notification:"https://erojgar.cg.gov.in/LandingSite/en/Home.aspx"},
 {id:"state-delhi",title:"Delhi Employment Portal",organization:"Government of NCT of Delhi",level:"10th / 12th / Graduate",sector:"State",location:"Delhi",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Delhi employment portal for job and employment services.",official:"https://onlineemploymentportal.delhi.gov.in/",notification:"https://onlineemploymentportal.delhi.gov.in/"},
 {id:"state-gujarat",title:"Gujarat Employment Portal",organization:"Government of Gujarat",level:"10th / 12th / Graduate",sector:"State",location:"Gujarat",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Gujarat employment services portal listed in the government NCS directory.",official:"https://anubandham.gujarat.gov.in/",notification:"https://anubandham.gujarat.gov.in/"},
 {id:"state-haryana",title:"Haryana Employment Portal",organization:"Government of Haryana",level:"10th / 12th / Graduate",sector:"State",location:"Haryana",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Haryana employment portal for state job and employment services.",official:"https://www.hrex.gov.in/",notification:"https://www.hrex.gov.in/"},
 {id:"state-himachal",title:"Himachal Pradesh Employment Portal",organization:"Government of Himachal Pradesh",level:"10th / 12th / Graduate",sector:"State",location:"Himachal Pradesh",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Himachal Pradesh employment services portal.",official:"https://eemis.hp.gov.in/",notification:"https://eemis.hp.gov.in/"},
 {id:"state-jammu-kashmir",title:"Jammu & Kashmir Employment Portal",organization:"Government of Jammu & Kashmir",level:"10th / 12th / Graduate",sector:"State",location:"Jammu & Kashmir",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official J&K employment portal listed in the National Career Service directory.",official:"https://jakemp.nic.in/",notification:"https://jakemp.nic.in/"},
 {id:"state-jharkhand",title:"Jharkhand Recruitment Portal",organization:"Government of Jharkhand",level:"10th / 12th / Graduate",sector:"State",location:"Jharkhand",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Jharkhand recruitment portal listed by the government NCS directory.",official:"http://recruitment.jharkhand.gov.in/",notification:"http://recruitment.jharkhand.gov.in/"},
 {id:"state-karnataka",title:"Karnataka Employment Services",organization:"Government of Karnataka",level:"10th / 12th / Diploma / Graduate",sector:"State",location:"Karnataka",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Karnataka employment services portal listed by NCS.",official:"https://itiemp.karnataka.gov.in/13/employment-wing/en",notification:"https://itiemp.karnataka.gov.in/13/employment-wing/en"},
 {id:"state-kerala",title:"Kerala Employment Portal",organization:"Government of Kerala",level:"10th / 12th / Graduate",sector:"State",location:"Kerala",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Kerala employment services portal.",official:"https://www.employment.kerala.gov.in/",notification:"https://www.employment.kerala.gov.in/"},
 {id:"state-madhya-pradesh",title:"Madhya Pradesh Employment Portal",organization:"Government of Madhya Pradesh",level:"10th / 12th / Graduate",sector:"State",location:"Madhya Pradesh",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official MP employment portal for state opportunities.",official:"https://mprojgar.gov.in/home",notification:"https://mprojgar.gov.in/home"},
 {id:"state-maharashtra",title:"Maharashtra Employment Portal",organization:"Government of Maharashtra",level:"10th / 12th / Graduate",sector:"State",location:"Maharashtra",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Maharashtra employment and job portal.",official:"https://rojgar.mahaswayam.gov.in/#/home/index",notification:"https://rojgar.mahaswayam.gov.in/#/home/index"},
 {id:"state-odisha",title:"Odisha Employment Mission Portal",organization:"Government of Odisha",level:"10th / 12th / Graduate",sector:"State",location:"Odisha",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Odisha employment mission portal listed by NCS.",official:"https://empmission.odisha.gov.in/Exchange/Entry.jsp",notification:"https://empmission.odisha.gov.in/Exchange/Entry.jsp"},
 {id:"state-punjab",title:"Punjab Employment Portal",organization:"Government of Punjab",level:"10th / 12th / Graduate",sector:"State",location:"Punjab",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Punjab employment portal listed in the government NCS directory.",official:"https://www.pgrkam.com/",notification:"https://www.pgrkam.com/"},
 {id:"state-rajasthan",title:"Rajasthan Employment Portal",organization:"Government of Rajasthan",level:"10th / 12th / Graduate",sector:"State",location:"Rajasthan",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Rajasthan employment services portal.",official:"https://rajemployment.rajasthan.gov.in/",notification:"https://rajemployment.rajasthan.gov.in/"},
 {id:"state-tamil-nadu",title:"Tamil Nadu Employment Portal",organization:"Government of Tamil Nadu",level:"10th / 12th / Graduate",sector:"State",location:"Tamil Nadu",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official Tamil Nadu employment services portal.",official:"https://tnvelaivaaippu.gov.in/",notification:"https://tnvelaivaaippu.gov.in/"},
 {id:"state-west-bengal",title:"West Bengal Employment Bank",organization:"Government of West Bengal",level:"10th / 12th / Graduate",sector:"State",location:"West Bengal",status:"Live",deadline:"Job-wise",pay:"Job-wise",description:"Official West Bengal employment portal listed by the National Career Service directory.",official:"https://employmentbankwb.gov.in/index.php",notification:"https://employmentbankwb.gov.in/index.php"}
];
const filters=["All","10th","12th","Graduate","Diploma","Central","State","National","Internship"];

export default function CareerPage(){
 const [filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Vacancy|null>(null);
 const [saved,setSaved]=useState<string[]>([]);
 const visible=useMemo(()=>{const q=query.toLowerCase().trim();return vacancies.filter(v=>(filter==="All"||v.level.includes(filter)||v.sector===filter)&&(!q||Object.values(v).join(" ").toLowerCase().includes(q)))},[filter,query]);
 const toggle=(id:string)=>{setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])};
 return <main className="page career-page">
  <style>{`
   .career-hero{display:flex;justify-content:space-between;gap:25px;padding:30px;border:1px solid rgba(255,255,255,.09);border-radius:26px;background:radial-gradient(circle at 85% 15%,rgba(34,211,238,.15),transparent 30%),linear-gradient(145deg,rgba(29,23,58,.96),rgba(10,10,27,.97));box-shadow:0 18px 55px rgba(0,0,0,.28)}
   .career-hero h1{margin:7px 0 12px;max-width:720px;font-size:clamp(30px,5vw,52px);line-height:1.02;letter-spacing:-2px;background:linear-gradient(100deg,#fff,#c4b5fd,#67e8f9);-webkit-background-clip:text;background-clip:text;color:transparent}.career-hero p{max-width:700px;color:#aaa7bd;font-size:13px;line-height:1.7}.career-pills{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.career-pills span,.career-status{padding:7px 10px;border-radius:999px;background:rgba(139,92,246,.1);border:1px solid rgba(139,92,246,.22);color:#d8ccff;font-size:9px;font-weight:800}.career-orbit{width:145px;height:145px;min-width:145px;border-radius:50%;display:grid;place-content:center;text-align:center;border:1px solid rgba(34,211,238,.25);background:radial-gradient(circle,rgba(34,211,238,.18),rgba(124,58,237,.08),transparent 68%);animation:floatSoft 4s ease-in-out infinite}.career-orbit b,.career-orbit span{display:block;font-size:8px;letter-spacing:3px;color:#aaa7bd}.career-orbit div{font-size:38px;color:#67e8f9}
   .career-toolbar{display:flex;gap:10px;align-items:center;margin:18px 0}.career-search{display:flex;gap:8px;align-items:center;flex:1;padding:12px 14px;border:1px solid rgba(255,255,255,.09);border-radius:14px;background:rgba(255,255,255,.045);color:#a78bfa}.career-search input{width:100%;border:0!important;outline:0;background:transparent!important}.career-filters{display:flex;gap:6px;flex-wrap:wrap}.career-filters button{border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.045);color:#aaa7bd;border-radius:999px;padding:9px 10px;font-size:9px;font-weight:800}.career-filters button.selected{background:linear-gradient(135deg,#7c3aed,#c026d3);color:#fff}
   .career-alert{display:flex;justify-content:space-between;gap:15px;padding:14px 16px;margin-bottom:25px;border:1px solid rgba(245,158,11,.18);border-radius:16px;background:rgba(245,158,11,.07)}.career-alert strong{font-size:11px}.career-alert p{margin:4px 0;color:#8f8ba3;font-size:9px}.career-alert a{color:#e9d5ff;font-size:9px;font-weight:800;white-space:nowrap}
   .career-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:12px}.career-head h2{margin:5px 0;font-size:23px}.career-head span{color:#8f8ba3;font-size:9px}.career-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.career-card{padding:18px;border:1px solid rgba(255,255,255,.08);border-radius:20px;background:linear-gradient(145deg,rgba(25,23,52,.92),rgba(11,11,28,.96));transition:.2s}.career-card:hover{transform:translateY(-3px);border-color:rgba(139,92,246,.25)}.career-card-top{display:flex;justify-content:space-between}.career-save{width:30px;height:30px;border-radius:9px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.04);color:#aaa7bd}.career-save.saved{color:#fbbf24}.career-card h3{margin:14px 0 5px;font-size:17px}.career-org{color:#a78bfa!important;font-size:10px!important;font-weight:700}.career-card p{color:#9995aa;font-size:10px;line-height:1.6}.career-meta{display:flex;flex-wrap:wrap;gap:6px;margin:13px 0}.career-meta span{padding:7px 8px;border-radius:9px;background:rgba(255,255,255,.045);color:#b8b3c5;font-size:8px}.career-actions{display:flex;gap:8px}.career-actions button,.career-actions a{flex:1;text-align:center;padding:10px;border-radius:10px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.045);color:#e9d5ff;font-size:9px;font-weight:800}.career-actions button{cursor:pointer;background:rgba(124,58,237,.2)}
   .career-next{margin-top:25px;padding:20px;border-radius:20px;border:1px solid rgba(255,255,255,.08);background:linear-gradient(145deg,rgba(34,211,238,.06),rgba(139,92,246,.08))}.career-next h2{margin:5px 0}.career-next p{color:#9691a7;font-size:10px}.career-next-list{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.career-next-list span{padding:12px;border-radius:12px;background:rgba(255,255,255,.045);color:#a78bfa;font-size:9px}.career-next-list b,.career-next-list small{display:block}.career-next-list b{color:#fff;margin:5px 0}.career-next-list small{color:#898498}
   .career-modal-bg{position:fixed;inset:0;z-index:3000;display:grid;place-items:center;padding:18px;background:rgba(2,2,10,.75);backdrop-filter:blur(12px)}.career-modal{position:relative;width:min(640px,100%);padding:24px;border-radius:23px;border:1px solid rgba(255,255,255,.11);background:linear-gradient(145deg,#1a1736,#0b0b20);box-shadow:0 30px 90px rgba(0,0,0,.55)}.career-close{position:absolute;right:14px;top:14px;width:32px;height:32px;border-radius:9px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.05);color:#fff}.career-detail{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:17px 0}.career-detail span{padding:11px;border-radius:11px;background:rgba(255,255,255,.045)}.career-detail small,.career-detail b{display:block}.career-detail small{font-size:8px;color:#858197}.career-detail b{font-size:10px;margin-top:4px}.career-modal-actions{display:flex;gap:8px}.career-modal-actions a{flex:1;text-align:center;padding:10px;border-radius:10px;background:rgba(124,58,237,.2);color:#e9d5ff;font-size:9px;font-weight:800}
   @media(max-width:800px){.career-hero{display:block;padding:22px}.career-orbit{display:none}.career-toolbar{display:block}.career-search{margin-bottom:10px}.career-grid{grid-template-columns:1fr}.career-alert{flex-direction:column}.career-alert a{white-space:normal}.career-next-list{grid-template-columns:1fr}}@media(max-width:520px){.career-filters{overflow:auto;flex-wrap:nowrap}.career-filters button{white-space:nowrap}.career-detail{grid-template-columns:1fr}.career-modal-actions{flex-direction:column}}
  `}</style>
  <section className="career-hero"><div><span className="section-eyebrow">CAREER & VACANCY UPDATES</span><h1>Find opportunities before the deadline.</h1><p>One place to discover government exams, recruitment notices and official job sources. Lakshya always sends you to the official notification before you apply.</p><div className="career-pills"><span>✓ Official sources</span><span>⌁ Qualification filters</span><span>⏰ Deadline tracking</span></div></div><div className="career-orbit"><div>↗</div><span>CAREER</span><b>UPDATES</b></div></section>
  <section className="career-toolbar"><label className="career-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search SSC, UPSC, 12th pass, diploma..." /></label><div className="career-filters">{filters.map(x=><button key={x} className={filter===x?"selected":""} onClick={()=>setFilter(x)}>{x}</button>)}</div></section>
  <section className="career-alert"><div><strong>Important: verify every application on the official notice.</strong><p>Eligibility, age, fee, dates, vacancies and selection rules can change. Lakshya does not invent or guarantee a vacancy.</p></div><a href="https://employmentnews.gov.in/newemp/AllJobs.aspx?k=All" target="_blank" rel="noreferrer">Open latest official listings ↗</a></section>
  <div className="career-head"><div><span className="section-eyebrow">OPPORTUNITY HUB</span><h2>Official sources & tracked updates</h2></div><span>{visible.length} source cards</span></div>
  <section className="career-grid">{visible.map(v=><article className="career-card" key={v.id}><div className="career-card-top"><span className="career-status">{v.status}</span><button className={saved.includes(v.id)?"career-save saved":"career-save"} onClick={()=>toggle(v.id)}>{saved.includes(v.id)?"★":"☆"}</button></div><h3>{v.title}</h3><p className="career-org">{v.organization}</p><p>{v.description}</p><div className="career-meta"><span>🎓 {v.level}</span><span>⌖ {v.location}</span><span>⏰ {v.deadline}</span></div><div className="career-actions"><button onClick={()=>setSelected(v)}>Full update</button><a href={v.notification} target="_blank" rel="noreferrer">Official notice ↗</a></div></article>)}</section>
  <section className="career-next"><span className="section-eyebrow">NEXT LAYER</span><h2>Personal vacancy alerts</h2><p>Save qualification and preferred areas so future updates can be filtered for you.</p><div className="career-next-list"><span>01<b>Qualification</b><small>10th · 12th · Diploma · Graduate</small></span><span>02<b>Preferred area</b><small>Central · State · Internship</small></span><span>03<b>Deadline alerts</b><small>New · Updated · Closing soon</small></span></div></section>
  {selected&&<div className="career-modal-bg" onMouseDown={()=>setSelected(null)}><div className="career-modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="career-close" onClick={()=>setSelected(null)}>×</button><span className="career-status">{selected.status}</span><h2>{selected.title}</h2><p className="career-org">{selected.organization} · {selected.location}</p><div className="career-detail"><span><small>Qualification</small><b>{selected.level}</b></span><span><small>Deadline</small><b>{selected.deadline}</b></span><span><small>Pay</small><b>{selected.pay}</b></span><span><small>Sector</small><b>{selected.sector}</b></span></div><p>{selected.description}</p><div className="career-modal-actions"><a href={selected.notification} target="_blank" rel="noreferrer">View official notice ↗</a><a href={selected.official} target="_blank" rel="noreferrer">Official website ↗</a></div></div></div>}
 </main>;
}