"use client";

import { useEffect, useState } from "react";
import type { MediaMetadata } from "../../../lib/storage";
import { optimizeCloudinaryUrl } from "../../../lib/storage";

export function MediaGallery({ media }: { media: MediaMetadata[] }) {
 const [active,setActive]=useState<MediaMetadata|null>(null); const [failed,setFailed]=useState<string[]>([]);
 useEffect(()=>{if(!active)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setActive(null)};window.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;window.removeEventListener("keydown",key)}},[active]);
 if(!media.length)return null;
 return <>
  <div className="media-grid">{media.map(item=><button className="media-tile" key={item.id} type="button" onClick={()=>setActive(item)} aria-label={`Open ${item.fileName} fullscreen`}>
   {failed.includes(item.id)?<div className="media-fallback"><span>⌁</span><strong>Media unavailable</strong><small>{item.fileName}</small></div>:item.resourceType==="video"?<video src={item.secureUrl} poster={item.thumbnailUrl} muted playsInline preload="metadata" onError={()=>setFailed(x=>x.includes(item.id)?x:[...x,item.id])}/>:item.resourceType==="image"?<img src={optimizeCloudinaryUrl(item.secureUrl,1000)} alt={item.fileName} loading="lazy" onError={()=>setFailed(x=>x.includes(item.id)?x:[...x,item.id])}/>:<div className="doc-tile"><span>DOC</span><strong>{item.fileName}</strong></div>}
   <span className="view-badge">↗</span>
  </button>)}</div>
  {active&&<div className="media-modal" role="dialog" aria-modal="true" aria-label="Fullscreen media viewer" onClick={()=>setActive(null)}>
   <div className="viewer-top"><span>{active.fileName}</span><button type="button" onClick={()=>setActive(null)} aria-label="Close fullscreen">×</button></div>
   <div className="media-modal-content" onClick={e=>e.stopPropagation()}>
    {active.resourceType==="video"?<video src={active.secureUrl} poster={active.thumbnailUrl} controls autoPlay playsInline/>:active.resourceType==="image"?<img src={active.secureUrl} alt={active.fileName}/>:<a className="document-open" href={active.secureUrl} target="_blank" rel="noreferrer">Open {active.fileName}</a>}
   </div>
  </div>}
  <style jsx>{`.media-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:8px;margin-top:11px}.media-tile{position:relative;border:0;padding:0;aspect-ratio:1/1;overflow:hidden;border-radius:13px;background:#edf1f6;cursor:pointer}.media-tile img,.media-tile video{width:100%;height:100%;object-fit:cover;display:block;transition:transform .25s ease;background:#0d1422}.media-tile video{object-position:center}.media-tile:hover img,.media-tile:hover video{transform:scale(1.035)}.view-badge{position:absolute;right:8px;bottom:8px;width:27px;height:27px;border-radius:9px;display:grid;place-items:center;background:#172033bb;color:#fff;font-size:14px;backdrop-filter:blur(7px)}.media-fallback{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;padding:14px;text-align:center;background:linear-gradient(135deg,#f1f3ff,#fbf1ff);color:#65718a}.media-fallback span{width:34px;height:34px;border-radius:11px;display:grid;place-items:center;background:#e6e9ff;color:#596cff;font-size:18px}.media-fallback strong{font-size:10px}.media-fallback small{max-width:90%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:8px;color:#8b95a7}.doc-tile{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:12px;gap:7px}.doc-tile span{font-size:9px;font-weight:900;background:#202a3b;color:#fff;border-radius:6px;padding:4px 6px}.doc-tile strong{font-size:9px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:90%}.media-modal{position:fixed;inset:0;z-index:9999;background:rgba(6,10,18,.96);display:grid;grid-template-rows:56px 1fr;padding:0}.viewer-top{display:flex;align-items:center;justify-content:space-between;padding:0 16px;color:#fff;background:rgba(12,18,30,.72);backdrop-filter:blur(14px);font-size:10px;font-weight:800}.viewer-top span{max-width:78%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.viewer-top button{width:36px;height:36px;border:1px solid #ffffff22;border-radius:50%;background:#ffffff12;color:#fff;font-size:25px;line-height:1;cursor:pointer}.media-modal-content{min-height:0;width:100%;height:100%;display:grid;place-items:center;overflow:hidden}.media-modal-content img,.media-modal-content video{display:block;max-width:100%;max-height:100%;width:auto;height:auto;object-fit:contain;border-radius:0}.document-open{background:#fff;color:#18212b;text-decoration:none;padding:14px 18px;border-radius:10px;font-size:12px;font-weight:900}@media(max-width:760px){.media-grid{grid-template-columns:repeat(2,1fr);gap:6px}.media-modal{grid-template-rows:52px 1fr}.media-modal-content img,.media-modal-content video{width:100%;height:auto;max-height:calc(100vh - 52px)}}`}</style>
 </>;
}