export type ProjectCategory = "Science" | "Mathematics" | "Social Science" | "English" | "Computer" | "Environment" | "Exhibition" | "Other";
export type ProjectTemplate = { id:string; name:string; category:ProjectCategory; subject:string; classLevel:string; description:string; icon:string; sections:string[]; tags:string[] };
export const PROJECT_CATEGORIES: ProjectCategory[] = ["Science","Mathematics","Social Science","English","Computer","Environment","Exhibition","Other"];
export const PROJECT_TEMPLATES: ProjectTemplate[] = [
{id:"science-research",name:"Science Research Project",category:"Science",subject:"Science",classLevel:"6–12",description:"Research a science topic, collect explanations, add diagrams and finish with a clear conclusion and sources.",icon:"🔬",sections:["Title","Introduction","Research Question","What I Learned","Diagram / Image","Result","Conclusion","Sources"],tags:["science","research","diagram"]},
{id:"science-experiment",name:"Science Experiment Report",category:"Science",subject:"Science",classLevel:"6–12",description:"Build a school experiment report with aim, hypothesis, method, observations, result, conclusion and sources.",icon:"🧪",sections:["Title","Aim","Background","Hypothesis","Materials","Method","Observation / Data","Result","Conclusion","Sources"],tags:["experiment","observation","result"]},
{id:"working-model",name:"Working Model Explanation",category:"Science",subject:"Science",classLevel:"6–12",description:"Explain how a school working model works, its parts, principle, applications and learning outcome.",icon:"⚙️",sections:["Title","Introduction","Principle","Parts","How It Works","Diagram","Applications","Conclusion","Sources"],tags:["model","exhibition","science"]},
{id:"environment",name:"Environmental Project",category:"Environment",subject:"Environmental Studies",classLevel:"6–12",description:"Research an environmental issue using causes, effects, local observations, solutions and a conclusion.",icon:"🌱",sections:["Title","Introduction","Problem","Causes","Effects","Data / Observation","Solutions","Conclusion","Sources"],tags:["environment","pollution","research"]},
{id:"maths-activity",name:"Mathematics Activity Project",category:"Mathematics",subject:"Mathematics",classLevel:"6–12",description:"Turn a maths concept into a clear activity with concept, formula, example, calculation and result.",icon:"📐",sections:["Title","Concept","Formula / Rule","Example","Activity","Calculation","Result","Conclusion","Sources"],tags:["maths","formula","activity"]},
{id:"social-research",name:"Social Science Research",category:"Social Science",subject:"Social Science",classLevel:"6–12",description:"Create a structured social-science project with background, causes, effects, data, case study and sources.",icon:"🌍",sections:["Title","Background","Research Question","Causes","Effects","Data / Case Study","Findings","Conclusion","Sources"],tags:["history","geography","civics","research"]},
{id:"biography",name:"Biography / Personality Project",category:"English",subject:"English / General",classLevel:"6–12",description:"Research a person and present early life, achievements, contribution, timeline and sources.",icon:"👤",sections:["Title","Introduction","Early Life","Education","Major Work","Achievements","Contribution","Conclusion","Sources"],tags:["biography","personality","timeline"]},
{id:"literature",name:"English Literature Project",category:"English",subject:"English",classLevel:"8–12",description:"Organize a literature project around context, themes, characters, key ideas, analysis and references.",icon:"📖",sections:["Title","Context","Author","Characters","Themes","Key Ideas","Analysis","Conclusion","References"],tags:["literature","analysis","english"]},
{id:"computer-project",name:"Computer / Technology Project",category:"Computer",subject:"Computer",classLevel:"6–12",description:"Research a technology topic and explain its purpose, working, uses, benefits, limitations and future scope.",icon:"💻",sections:["Title","Introduction","What Is It?","How It Works","Uses","Benefits","Limitations","Future Scope","Conclusion","Sources"],tags:["computer","technology","research"]},
{id:"exhibition-board",name:"Science Exhibition Board",category:"Exhibition",subject:"Science",classLevel:"6–12",description:"Create concise exhibition-board content with problem, idea, method, observations, result, visuals and takeaway.",icon:"🧩",sections:["Project Title","Problem / Question","Idea","Method","Observation","Result","Diagram / Photo","Conclusion","Sources"],tags:["exhibition","board","science"]},
{id:"presentation",name:"School Presentation",category:"Exhibition",subject:"Any Subject",classLevel:"6–12",description:"Turn researched material into presentation-ready sections with speaker notes and a final summary.",icon:"📊",sections:["Title","Introduction","Key Point 1","Key Point 2","Data / Visual","Key Findings","Conclusion","Sources","Viva Questions"],tags:["presentation","slides","viva"]}
];
export const getProjectTemplate=(id:string)=>PROJECT_TEMPLATES.find(t=>t.id===id);
