"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

const books = [
  { className: "Class XII", subject: "Physics", title: "Physics Part-I", url: "https://ncert.nic.in/textbook.php?keph1=1-7", chapters: ["Electric Charges and Fields", "Electrostatic Potential and Capacitance", "Current Electricity", "Moving Charges and Magnetism", "Magnetism and Matter", "Electromagnetic Induction", "Alternating Current"] },
  { className: "Class XII", subject: "Physics", title: "Physics Part-II", url: "https://ncert.nic.in/textbook.php?leph2=0-7", chapters: ["Electromagnetic Waves", "Ray Optics and Optical Instruments", "Wave Optics", "Dual Nature of Radiation and Matter", "Atoms", "Nuclei", "Semiconductor Electronics"] },
  { className: "Class XII", subject: "Chemistry", title: "Chemistry Part-I", url: "https://ncert.nic.in/textbook.php?kech1=5-7", chapters: ["Solutions", "Electrochemistry", "Chemical Kinetics", "d- and f-Block Elements", "Coordination Compounds"] },
  { className: "Class XII", subject: "Chemistry", title: "Chemistry Part-II", url: "https://ncert.nic.in/textbook.php?lech2=ps-6", chapters: ["Haloalkanes and Haloarenes", "Alcohols, Phenols and Ethers", "Aldehydes, Ketones and Carboxylic Acids", "Amines", "Biomolecules", "Polymers", "Chemistry in Everyday Life"] },
  { className: "Class XII", subject: "Biology", title: "Biology", url: "https://ncert.nic.in/textbook.php?lebo1=8-12", chapters: ["Sexual Reproduction in Flowering Plants", "Human Reproduction", "Reproductive Health", "Principles of Inheritance and Variation", "Molecular Basis of Inheritance", "Evolution", "Human Health and Disease", "Biotechnology: Principles and Processes", "Biotechnology and its Applications", "Ecology and Environment"] },
];

export default function NcertBooksPage() {
  const [query, setQuery] = useState("");
  const [subject, setSubject] = useState("All");
  const filtered = useMemo(() => books.filter(b => (subject === "All" || b.subject === subject) && `${b.title} ${b.subject} ${b.chapters.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query, subject]);

  return <main className="page">
    <header><Link href="/study">← Study</Link><span className="eyebrow">LAKSHYA • NCERT LIBRARY</span><h1>NCERT Books</h1><p>Official NCERT textbook access with chapter-wise Lakshya study flow.</p></header>
    <section className="hero"><div><span className="badge">OFFICIAL NCERT</span><h2>Read → ask AI → capture → revise</h2><p>Open the official NCERT source, choose your chapter, then jump into that chapter's workspace to save learning permanently.</p></div><a href="https://ncert.nic.in/textbook.php" target="_blank" rel="noreferrer" className="primary">Open NCERT ↗</a></section>
    <div className="filters"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search book or chapter…" />{["All", "Physics", "Chemistry", "Biology"].map(s => <button key={s} className={subject === s ? "active" : ""} onClick={() => setSubject(s)}>{s}</button>)}</div>
    <section className="grid">{filtered.map(book => <article key={book.title}><div className="meta"><span>{book.className}</span><b>{book.subject}</b></div><h3>{book.title}</h3><div className="chapters">{book.chapters.map(ch => <div className="chapter" key={ch}><span>{ch}</span><div><a href={book.url} target="_blank" rel="noreferrer">Read ↗</a><Link href={`/study/chapter?subject=${encodeURIComponent(book.subject)}&chapter=${encodeURIComponent(ch)}`}>Study →</Link></div></div>)}</div><a className="book" href={book.url} target="_blank" rel="noreferrer">Open complete official book ↗</a></article>)}</section>
    <section className="note"><b>📚 Lakshya NCERT workflow</b><ol><li>NCERT से concept पढ़ो.</li><li><b>Study →</b> से उसी chapter का workspace खोलो.</li><li>Lakshya AI से concept समझो.</li><li>AI Capture से MCQ, Flashcard, Key Point या Quick Revision save करो.</li><li>Saved material उसी chapter में बना रहेगा, जब तक तुम उसे delete/export नहीं करते.</li></ol></section>
    <style jsx>{`body{background:#f6f7fb}.page{max-width:1080px;margin:auto;padding:28px 22px 70px;color:#171a2b}.page header>a{color:#697183;text-decoration:none;font-size:11px;font-weight:800}.eyebrow{display:block;margin-top:22px;font-size:8px;letter-spacing:.16em;color:#9299a8;font-weight:900}.page h1{font-size:32px;margin:6px 0}.page header p{font-size:10px;color:#858c9c;margin:0}.hero{display:flex;align-items:center;justify-content:space-between;gap:18px;background:#fff;border:1px solid #e4e6ef;border-radius:16px;padding:20px;margin:20px 0 14px}.badge{display:inline-block;background:#f0efff;color:#6258df;border-radius:6px;padding:5px 7px;font-size:8px;font-weight:900;letter-spacing:.1em}.hero h2{font-size:20px;margin:9px 0 6px}.hero p{max-width:700px;font-size:10px;line-height:1.6;color:#858c9c;margin:0}.primary{display:inline-block;background:#1b1d2b;color:#fff;text-decoration:none;border-radius:9px;padding:11px 14px;font-size:9px;font-weight:800;white-space:nowrap}.filters{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.filters input{flex:1;min-width:220px;border:1px solid #e0e3ec;border-radius:9px;padding:10px 12px;font-size:10px;outline:none}.filters button{border:1px solid #dddff0;background:#fff;border-radius:9px;padding:9px 12px;font-size:9px;font-weight:800}.filters button.active{background:#1b1d2b;color:#fff}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.grid article{background:#fff;border:1px solid #e4e6ef;border-radius:14px;padding:16px}.meta{display:flex;justify-content:space-between;font-size:8px;color:#9299a8}.meta b{color:#6258df}.grid h3{font-size:16px;margin:8px 0 10px}.chapter{display:flex;align-items:center;justify-content:space-between;gap:8px;border-top:1px solid #eef0f4;padding:9px 0;font-size:9px}.chapter>span{line-height:1.4}.chapter div{display:flex;gap:7px;white-space:nowrap}.chapter a,.book{font-size:8px;font-weight:900;color:#5d55c9;text-decoration:none}.book{display:block;border-top:1px solid #eef0f4;padding-top:11px;margin-top:3px}.note{margin-top:14px;background:#faf9ff;border:1px solid #e1defc;border-radius:14px;padding:16px;font-size:10px;line-height:1.7}.note ol{margin:8px 0 0;padding-left:20px;color:#626a7a}@media(max-width:700px){.page{padding:20px 14px 70px}.hero{display:block}.hero .primary{margin-top:14px}.grid{grid-template-columns:1fr}.chapter{align-items:flex-start}.chapter div{flex-direction:column;align-items:flex-end}}`}</style>
  </main>;
}
