"use client";
import { useEffect, useState } from "react";
import { onAuthStateChanged, sendPasswordResetEmail, signOut } from "firebase/auth";
import { ref, set } from "firebase/database";
import { auth, realtimeDb } from "../../lib/firebase";

export default function SettingsPage(){
 const [uid,setUid]=useState<string|null>(null); const [email,setEmail]=useState(""); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const [privacy,setPrivacy]=useState({profile:true,messages:true}); const [notifications,setNotifications]=useState({community:true,study:true,ai:true}); const [appearance,setAppearance]=useState("system"); const [language,setLanguage]=useState("hi-en");
 useEffect(()=>onAuthStateChanged(auth,u=>{setUid(u?.uid||null);setEmail(u?.email||""); if(u) import("../../lib/firebase").then(()=>{});}),[]);
 useEffect(()=>{const saved=localStorage.getItem("lakshya_settings");if(saved)try{const x=JSON.parse(saved);setPrivacy(x.privacy||privacy);setNotifications(x.notifications||notifications);setAppearance(x.appearance||"system");setLanguage(x.language||"hi-en")}catch{}},[]);
 function persist(next:any){localStorage.setItem("lakshya_settings",JSON.stringify(next));setMessage("Settings saved.");}
 async function save(){setSaving(true);setMessage("");const data={privacy,notifications,appearance,language};persist(data);if(uid)try{await set(ref(realtimeDb,`users/${uid}/settings`),data)}catch(e){setMessage(e instanceof Error?e.message:"Settings saved locally; cloud sync failed.")}finally{setSaving(false)}}
 async function resetPassword(){if(!email){setMessage("Please sign in first.");return}try{await sendPasswordResetEmail(auth,email);setMessage("Password reset email sent.")}catch(e){setMessage(e instanceof Error?e.message:"Could not send reset email.")}}
 async function logout(){await signOut(auth);window.location.href="/auth/sign-in"}
 return <main className="settings"><header><a href="/" className="back">← Dashboard</a><p className="eyebrow">LAKSHYA CONTROL CENTER</p><h1>Settings</h1><p>Account, privacy, notifications and your study experience — all in one place.</p></header>
 <section className="grid">
 <div className="card"><span className="eyebrow">ACCOUNT</span><h2>Account & security</h2><div className="row"><div><b>{email||"Not signed in"}</b><small>Firebase account</small></div><button onClick={()=>void resetPassword()}>Reset password</button></div><div className="row"><div><b>Profile</b><small>Edit your public student profile</small></div><a href="/profile">Open profile</a></div><div className="row danger"><div><b>Sign out</b><small>End your current session on this device</small></div><button onClick={()=>void logout()}>Sign out</button></div></div>
 <div className="card"><span className="eyebrow">PRIVACY</span><h2>Who can interact with you</h2><Toggle label="Public profile" desc="Allow other students to open your profile from posts" value={privacy.profile} onChange={v=>setPrivacy(x=>({...x,profile:v}))}/><Toggle label="Direct messages" desc="Allow approved community interactions" value={privacy.messages} onChange={v=>setPrivacy(x=>({...x,messages:v}))}/></div>
 <div className="card"><span className="eyebrow">NOTIFICATIONS</span><h2>Stay updated</h2><Toggle label="Study reminders" desc="Timer, revision and learning reminders" value={notifications.study} onChange={v=>setNotifications(x=>({...x,study:v}))}/><Toggle label="Community activity" desc="Likes, comments, follows and discussions" value={notifications.community} onChange={v=>setNotifications(x=>({...x,community:v}))}/><Toggle label="AI updates" desc="AI study and generated-material updates" value={notifications.ai} onChange={v=>setNotifications(x=>({...x,ai:v}))}/></div>
 <div className="card"><span className="eyebrow">EXPERIENCE</span><h2>App preferences</h2><label>Appearance<select value={appearance} onChange={e=>setAppearance(e.target.value)}><option value="system">System default</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="hi-en">Hindi + English</option><option value="hi">Hindi</option><option value="en">English</option></select></label><small>These preferences are stored for your Lakshya experience.</small></div>
 </section><div className="savebar"><button className="save" disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save all settings"}</button>{message&&<span>{message}</span>}</div>
 <style jsx global>{`.settings{max-width:1050px;margin:auto;padding:28px 24px 70px;color:#17202a}.back{color:#687789;font-size:12px;font-weight:800}.settings header{margin:18px 0 24px}.eyebrow{font-size:9px;letter-spacing:.16em;font-weight:900;color:#65758a;margin:0 0 7px}.settings h1{font-size:32px;letter-spacing:-.04em;margin:0}.settings header>p:last-child{color:#748294;font-size:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.card{padding:20px;border:1px solid #dce6f2;border-radius:18px;background:linear-gradient(145deg,#ffffffd9,#f4f8ffd9);box-shadow:0 10px 30px #52637c12}.card h2{font-size:17px;margin:0 0 15px}.row{display:flex;align-items:center;justify-content:space-between;gap:15px;border-top:1px solid #e4ebf2;padding:13px 0}.row b,.row small{display:block}.row b{font-size:11px}.row small{font-size:9px;color:#7b8794;margin-top:3px}.row button,.row a{border:1px solid #cdd9eb;background:#eef3ff;color:#5364a8;border-radius:9px;padding:8px 10px;font-size:9px;font-weight:800;text-decoration:none}.row.danger button{background:#fff0f3;border-color:#f1c8d1;color:#bd4b67}.toggle{display:flex;align-items:center;gap:12px;border-top:1px solid #e4ebf2;padding:12px 0}.toggle>div:first-child{flex:1}.toggle b,.toggle small{display:block}.toggle b{font-size:11px}.toggle small{font-size:9px;color:#7b8794;margin-top:3px}.switch{width:40px;height:22px;border:0;border-radius:20px;padding:2px;background:#cbd5e1}.switch.on{background:#536dfe}.knob{display:block;width:18px;height:18px;border-radius:50%;background:#fff;transition:transform .18s}.switch.on .knob{transform:translateX(18px)}label{display:block;font-size:10px;font-weight:800;color:#687789;margin:12px 0}select{display:block;width:100%;margin-top:6px;padding:10px;border:1px solid #d5dfeb;border-radius:10px;background:#f8fbff;font-size:11px}.card>small{font-size:9px;color:#7b8794}.savebar{display:flex;align-items:center;gap:15px;margin-top:18px}.save{border:0;border-radius:11px;padding:12px 17px;background:linear-gradient(135deg,#536dfe,#8b5cf6);color:#fff;font-weight:800}.savebar span{font-size:10px;color:#536dfe;font-weight:800}@media(max-width:720px){.settings{padding:20px 14px 55px}.grid{grid-template-columns:1fr}.settings h1{font-size:28px}.savebar{position:sticky;bottom:10px;background:#ffffffdd;backdrop-filter:blur(12px);padding:10px;border-radius:12px;box-shadow:0 5px 25px #0001}.save{width:100%}}`}</style></main>
}
function Toggle({label,desc,value,onChange}:{label:string;desc:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="toggle"><div><b>{label}</b><small>{desc}</small></div><button className={value?"switch on":"switch"} onClick={()=>onChange(!value)} aria-pressed={value}><span className="knob"/></button></div>}
